version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    working_directory: ~/app
    steps:
      - checkout
      - run: wget https://packages.erlang-solutions.com/erlang-solutions_2.0_all.deb && sudo dpkg -i erlang-solutions_2.0_all.deb
      - run: sudo apt-get -qq -y update && sudo apt-get -qq -y install esl-erlang && sudo apt-get -qq -y install elixir
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - restore_cache:
          keys:
            - v1-build-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
            - v1-build-cache-{{ .Branch }}
            - v1-build-cache
      - run:
          name: Build ae-channel-service
          command: make clean deps
      - save_cache:
          key: v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths: "deps"
      - save_cache:
          key: v1-mix-cache-{{ .Branch }}
          paths: "deps"
      - save_cache:
          key: v1-mix-cache
          paths: "deps"
      - save_cache:
          key: v1-build-cache-{{ .Branch }}
          paths: "_build"
      - save_cache:
          key: v1-build-cache
          paths: "_build"
      - run:
          name: Run tests
          command: make test
      - store_test_results:
          path: _build/test/lib/ae_socket_connector
