version: 2.1
jobs:
  build:
    docker:
      image: circleci/elixir
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-build-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
            - v1-build-cache-{{ .Branch }}
            - v1-build-cache
      - run:
          name: Build ae-channel-service
          command: make clean deps
      - save_cache:
          key: v1-build-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths:
            - "_build"
            - "deps"
      - save_cache:
          key: v1-build-cache-{{ .Branch }}
          paths:
            - "_build"
            - "deps"
      - save_cache:
          key: v1-build-cache
          paths:
            - "_build"
            - "deps"
      - run:
          name: Run tests
          command: make test --exclude ignore
      - store_test_results:
          path: _build/test/lib/ae_socket_connector
